// KrishiBondhu — English + Bangla translations.
const Map<String, Map<String, dynamic>> i18n = {
  'en': {
    'appName': 'KrishiBondhu', 'tagline': "Farmer's weather & market friend",
    'continue': 'Continue', 'next': 'Next', 'back': 'Back', 'save': 'Save', 'cancel': 'Cancel',
    'done': 'Done', 'skip': 'Skip', 'delete': 'Delete', 'edit': 'Edit', 'confirm': 'Confirm',
    'today': 'Today', 'km': 'km', 'optional': 'optional', 'search': 'Search',
    'welcome': 'Welcome back', 'signInSub': 'Sign in to continue to your farm dashboard',
    'createAccount': 'Create your account', 'registerSub': "Let's set up your farming profile",
    'fullName': 'Full name', 'phoneEmail': 'Phone number or email', 'password': 'Password',
    'role': 'I am a', 'roleFarmer': 'Farmer', 'roleTrader': 'Trader', 'roleUser': 'General user',
    'login': 'Log in', 'register': 'Register', 'logout': 'Log out',
    'noAccount': "Don't have an account?", 'haveAccount': 'Already registered?',
    'forgot': 'Forgot password?', 'rememberMe': 'Keep me logged in',
    'errName': 'Please enter your name', 'errCred': 'Enter your phone or email',
    'errPass': 'Password must be at least 4 characters', 'errLogin': 'No account found. Please register first.',
    'errWrongPass': 'Incorrect password. Try again.', 'errDup': 'An account with this phone/email already exists.',
    'errCredFormat': 'Enter a valid phone number (01XXXXXXXXX) or email address.',
    'setLocation': 'Set your location', 'locationSub': 'We use it for weather and nearby markets',
    'useGps': 'Use my current location', 'enterManually': 'Enter location manually',
    'locating': 'Getting your location…', 'locationSet': 'Location set',
    'gpsFail': "Couldn't get GPS. Please enter manually.",
    'district': 'District / area', 'pickCrops': 'Pick your crops', 'cropsSub': 'Select the crops you grow',
    'selectAtLeastOne': 'Select at least one crop',
    'tabHome': 'Home', 'tabWeather': 'Weather', 'tabMarket': 'Market', 'tabTasks': 'Tasks', 'tabProfile': 'Profile',
    'hello': 'Hello', 'todayAdvisory': "Today's advisory", 'viewAll': 'View all',
    'quickActions': 'Quick actions', 'nearbyMarkets': 'Nearby markets', 'upcomingTasks': 'Upcoming tasks',
    'qWeather': 'Weather', 'qMarkets': 'Markets', 'qReport': 'Report price', 'qReminder': 'Reminder',
    'feelsLike': 'Feels like', 'humidity': 'Humidity', 'wind': 'Wind', 'rain': 'Rain',
    'noTasks': 'No tasks scheduled', 'noTasksSub': 'Add a reminder to stay on track',
    'weatherTitle': 'Weather & advisory', 'dayForecast': '5-day forecast',
    'advisoryFor': 'Advisory for your crops', 'playAudio': 'Play audio advisory',
    'noAction': 'No special action needed today. Continue routine farm work.',
    'severeTag': 'Emergency alert', 'lastUpdated': 'Updated', 'refresh': 'Refresh',
    'marketTitle': 'Market prices', 'selectCrop': 'Select crop', 'within': 'Within',
    'sortBy': 'Sort', 'sortDistance': 'Distance', 'sortPrice': 'Price', 'avgPrice': 'Avg price',
    'reportPrice': 'Report a price', 'bestPrice': 'Best price', 'noRecent': 'No recent price',
    'noRecentSub': 'Be the first to report today', 'distance': 'Distance', 'latestPrice': 'Latest price',
    'reportedBy': 'by', 'setTarget': 'Set target price', 'targetSet': 'Target price set',
    'targetHint': 'Get alerted when any nearby market reaches this price',
    'submitPrice': 'Submit price', 'priceFor': 'Price for', 'atMarket': 'at market',
    'pricePerKg': 'Price (BDT per kg)', 'addMarket': 'Add new market', 'marketName': 'Market name',
    'priceSubmitted': 'Price submitted, thank you!', 'errPrice': 'Enter a valid price',
    'impossiblePrice': 'That price looks unusually high. Submit anyway?',
    'compare': 'Compare prices', 'reportedAgo': 'ago', 'justNow': 'just now',
    'targetTitle': 'Target price', 'targetValue': 'Target price (BDT/kg)',
    'currentRange': 'Recent price range', 'updateTarget': 'Update target', 'removeTarget': 'Remove target',
    'errTarget': 'Enter a valid target price', 'targetRemoved': 'Target removed',
    'priceAlert': 'Price alert', 'priceAlertBody': 'reached your target of',
    'tasksTitle': 'Smart reminders', 'addReminder': 'Add reminder', 'taskType': 'Task type',
    'forCrop': 'For crop', 'repeat': 'Repeat', 'repeatNone': 'One time', 'repeatDaily': 'Every day',
    'repeatWeekly': 'Every week', 'time': 'Time', 'reminderSaved': 'Reminder saved',
    'reminderDeleted': 'Reminder deleted', 'autoMoved': 'Auto-rescheduled due to weather',
    'movedBecause': 'Moved to avoid', 'deleteReminder': 'Delete this reminder?',
    'profileTitle': 'Profile', 'myCrops': 'My crops', 'myLocation': 'My location',
    'editProfile': 'Edit profile', 'language': 'Language', 'settings': 'Settings',
    'alertsSettings': 'Alerts', 'weatherAlerts': 'Severe weather alerts', 'priceAlerts': 'Price alerts',
    'liveMode': 'Live weather', 'demoMode': 'Demo weather', 'dataSource': 'Weather source',
    'weatherModeHint': 'Demo shows sample conditions so all alerts can be tested. Live fetches real weather from Open-Meteo (free, no key needed).',
    'account': 'Account', 'memberSince': 'Member', 'changeCrops': 'Change crops',
    'savedLoc': 'Saved location', 'notifPermission': 'Enable notifications',
    'aboutApp': 'About', 'version': 'Version',
    'offline': 'You are offline — showing saved data', 'online': 'Back online',
    'profileUpdated': 'Profile updated',
    'syncLive': 'Live sync on', 'syncLocal': 'Local mode', 'syncingNow': 'Connecting to server…',
    'days': ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'],
    'condSunny': 'Sunny', 'condCloud': 'Cloudy', 'condRain': 'Rain', 'condStorm': 'Storm', 'condClear': 'Clear',
  },
  'bn': {
    'appName': 'কৃষিবন্ধু', 'tagline': 'কৃষকের আবহাওয়া ও বাজার বন্ধু',
    'continue': 'এগিয়ে যান', 'next': 'পরবর্তী', 'back': 'পিছনে', 'save': 'সংরক্ষণ', 'cancel': 'বাতিল',
    'done': 'সম্পন্ন', 'skip': 'এড়িয়ে যান', 'delete': 'মুছুন', 'edit': 'সম্পাদনা', 'confirm': 'নিশ্চিত করুন',
    'today': 'আজ', 'km': 'কিমি', 'optional': 'ঐচ্ছিক', 'search': 'খুঁজুন',
    'welcome': 'আবার স্বাগতম', 'signInSub': 'আপনার ড্যাশবোর্ডে যেতে লগইন করুন',
    'createAccount': 'অ্যাকাউন্ট তৈরি করুন', 'registerSub': 'আপনার কৃষি প্রোফাইল সেট করি',
    'fullName': 'পুরো নাম', 'phoneEmail': 'ফোন নম্বর বা ইমেইল', 'password': 'পাসওয়ার্ড',
    'role': 'আমি একজন', 'roleFarmer': 'কৃষক', 'roleTrader': 'ব্যবসায়ী', 'roleUser': 'সাধারণ ব্যবহারকারী',
    'login': 'লগইন', 'register': 'নিবন্ধন', 'logout': 'লগআউট',
    'noAccount': 'অ্যাকাউন্ট নেই?', 'haveAccount': 'ইতিমধ্যে নিবন্ধিত?',
    'forgot': 'পাসওয়ার্ড ভুলে গেছেন?', 'rememberMe': 'লগইন রাখুন',
    'errName': 'অনুগ্রহ করে আপনার নাম লিখুন', 'errCred': 'ফোন বা ইমেইল লিখুন',
    'errPass': 'পাসওয়ার্ড কমপক্ষে ৪ অক্ষরের হতে হবে', 'errLogin': 'কোনো অ্যাকাউন্ট নেই। আগে নিবন্ধন করুন।',
    'errWrongPass': 'ভুল পাসওয়ার্ড। আবার চেষ্টা করুন।', 'errDup': 'এই ফোন/ইমেইল দিয়ে অ্যাকাউন্ট আছে।',
    'errCredFormat': 'সঠিক ফোন নম্বর (০১XXXXXXXXX) বা ইমেইল দিন।',
    'setLocation': 'আপনার অবস্থান দিন', 'locationSub': 'আবহাওয়া ও কাছের বাজারের জন্য প্রয়োজন',
    'useGps': 'আমার বর্তমান অবস্থান ব্যবহার করুন', 'enterManually': 'নিজে অবস্থান লিখুন',
    'locating': 'অবস্থান খোঁজা হচ্ছে…', 'locationSet': 'অবস্থান সেট হয়েছে',
    'gpsFail': 'জিপিএস পাওয়া যায়নি। নিজে লিখুন।',
    'district': 'জেলা / এলাকা', 'pickCrops': 'আপনার ফসল বাছুন', 'cropsSub': 'আপনি যে ফসল চাষ করেন তা নির্বাচন করুন',
    'selectAtLeastOne': 'কমপক্ষে একটি ফসল নির্বাচন করুন',
    'tabHome': 'হোম', 'tabWeather': 'আবহাওয়া', 'tabMarket': 'বাজার', 'tabTasks': 'কাজ', 'tabProfile': 'প্রোফাইল',
    'hello': 'আসসালামু আলাইকুম', 'todayAdvisory': 'আজকের পরামর্শ', 'viewAll': 'সব দেখুন',
    'quickActions': 'দ্রুত কাজ', 'nearbyMarkets': 'কাছের বাজার', 'upcomingTasks': 'আসন্ন কাজ',
    'qWeather': 'আবহাওয়া', 'qMarkets': 'বাজার', 'qReport': 'দাম দিন', 'qReminder': 'রিমাইন্ডার',
    'feelsLike': 'অনুভূত', 'humidity': 'আর্দ্রতা', 'wind': 'বাতাস', 'rain': 'বৃষ্টি',
    'noTasks': 'কোনো কাজ নির্ধারিত নেই', 'noTasksSub': 'ট্র্যাকে থাকতে রিমাইন্ডার যোগ করুন',
    'weatherTitle': 'আবহাওয়া ও পরামর্শ', 'dayForecast': '৫ দিনের পূর্বাভাস',
    'advisoryFor': 'আপনার ফসলের জন্য পরামর্শ', 'playAudio': 'পরামর্শ শুনুন',
    'noAction': 'আজ বিশেষ কিছু করার নেই। স্বাভাবিক কাজ চালিয়ে যান।',
    'severeTag': 'জরুরি সতর্কতা', 'lastUpdated': 'হালনাগাদ', 'refresh': 'রিফ্রেশ',
    'marketTitle': 'বাজার দর', 'selectCrop': 'ফসল নির্বাচন', 'within': 'দূরত্ব',
    'sortBy': 'সাজান', 'sortDistance': 'দূরত্ব', 'sortPrice': 'দাম', 'avgPrice': 'গড় দাম',
    'reportPrice': 'দাম জানান', 'bestPrice': 'সেরা দাম', 'noRecent': 'সাম্প্রতিক দাম নেই',
    'noRecentSub': 'আজ প্রথম দাম জানান', 'distance': 'দূরত্ব', 'latestPrice': 'সর্বশেষ দাম',
    'reportedBy': 'জানিয়েছেন', 'setTarget': 'লক্ষ্য দাম দিন', 'targetSet': 'লক্ষ্য দাম সেট হয়েছে',
    'targetHint': 'কাছের বাজারে এই দাম পৌঁছালে সতর্কতা পাবেন',
    'submitPrice': 'দাম জমা দিন', 'priceFor': 'দাম—', 'atMarket': 'বাজার',
    'pricePerKg': 'দাম (টাকা প্রতি কেজি)', 'addMarket': 'নতুন বাজার যোগ', 'marketName': 'বাজারের নাম',
    'priceSubmitted': 'দাম জমা হয়েছে, ধন্যবাদ!', 'errPrice': 'সঠিক দাম লিখুন',
    'impossiblePrice': 'দামটি অস্বাভাবিক বেশি মনে হচ্ছে। তবুও জমা দেবেন?',
    'compare': 'দাম তুলনা', 'reportedAgo': 'আগে', 'justNow': 'এইমাত্র',
    'targetTitle': 'লক্ষ্য দাম', 'targetValue': 'লক্ষ্য দাম (টাকা/কেজি)',
    'currentRange': 'সাম্প্রতিক দামের পরিসর', 'updateTarget': 'লক্ষ্য হালনাগাদ', 'removeTarget': 'লক্ষ্য সরান',
    'errTarget': 'সঠিক লক্ষ্য দাম লিখুন', 'targetRemoved': 'লক্ষ্য সরানো হয়েছে',
    'priceAlert': 'দাম সতর্কতা', 'priceAlertBody': 'আপনার লক্ষ্য পূরণ করেছে—',
    'tasksTitle': 'স্মার্ট রিমাইন্ডার', 'addReminder': 'রিমাইন্ডার যোগ', 'taskType': 'কাজের ধরন',
    'forCrop': 'ফসল', 'repeat': 'পুনরাবৃত্তি', 'repeatNone': 'একবার', 'repeatDaily': 'প্রতিদিন',
    'repeatWeekly': 'প্রতি সপ্তাহে', 'time': 'সময়', 'reminderSaved': 'রিমাইন্ডার সংরক্ষিত',
    'reminderDeleted': 'রিমাইন্ডার মুছে ফেলা হয়েছে', 'autoMoved': 'আবহাওয়ার কারণে স্বয়ংক্রিয়ভাবে পিছিয়ে দেওয়া হয়েছে',
    'movedBecause': 'এড়াতে সরানো হয়েছে—', 'deleteReminder': 'এই রিমাইন্ডার মুছবেন?',
    'profileTitle': 'প্রোফাইল', 'myCrops': 'আমার ফসল', 'myLocation': 'আমার অবস্থান',
    'editProfile': 'প্রোফাইল সম্পাদনা', 'language': 'ভাষা', 'settings': 'সেটিংস',
    'alertsSettings': 'সতর্কতা', 'weatherAlerts': 'দুর্যোগ সতর্কতা', 'priceAlerts': 'দাম সতর্কতা',
    'liveMode': 'লাইভ আবহাওয়া', 'demoMode': 'ডেমো আবহাওয়া', 'dataSource': 'আবহাওয়ার উৎস',
    'weatherModeHint': 'ডেমো নমুনা আবহাওয়া দেখায় যাতে সব সতর্কতা পরীক্ষা করা যায়। লাইভ Open-Meteo থেকে আসল আবহাওয়া আনে (ফ্রি, কী লাগে না)।',
    'account': 'অ্যাকাউন্ট', 'memberSince': 'সদস্য', 'changeCrops': 'ফসল পরিবর্তন',
    'savedLoc': 'সংরক্ষিত অবস্থান', 'notifPermission': 'নোটিফিকেশন চালু করুন',
    'aboutApp': 'সম্পর্কে', 'version': 'সংস্করণ',
    'offline': 'আপনি অফলাইন — সংরক্ষিত তথ্য দেখানো হচ্ছে', 'online': 'আবার অনলাইন',
    'profileUpdated': 'প্রোফাইল হালনাগাদ হয়েছে',
    'syncLive': 'লাইভ সিঙ্ক চালু', 'syncLocal': 'লোকাল মোড', 'syncingNow': 'সার্ভারের সাথে সংযোগ হচ্ছে…',
    'days': ['রবি', 'সোম', 'মঙ্গল', 'বুধ', 'বৃহঃ', 'শুক্র', 'শনি'],
    'condSunny': 'রৌদ্রোজ্জ্বল', 'condCloud': 'মেঘলা', 'condRain': 'বৃষ্টি', 'condStorm': 'ঝড়', 'condClear': 'পরিষ্কার',
  },
};

const _bnDigits = ['০', '১', '২', '৩', '৪', '৫', '৬', '৭', '৮', '৯'];
String bnNum(Object n, String lang) {
  if (lang != 'bn') return '$n';
  return '$n'.replaceAllMapped(RegExp(r'[0-9]'), (m) => _bnDigits[int.parse(m[0]!)]);
}
